services:
  - type: web
    name: nana-pastry-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=512 dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
